const BASE_URL = 'http://127.0.0.1:8090';
export const BASE_API = BASE_URL + '/';
export const LOGIN = 'authenticate';
export const SIGNUP = 'register';
export const USER = 'user';
export const PRODUCTS = 'api/products';
export const PICTURES = 'downloadFile';
export const ORDER = 'api/orders';
export const CURRENT_USER = 'me';
